// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachMediaToPost = `-- name: AttachMediaToPost :one
INSERT INTO post_media (post_id, media_id, sort_order)
VALUES ($1, $2, $3)
RETURNING id, post_id, media_id, sort_order, created_at
`

type AttachMediaToPostParams struct {
	PostID    pgtype.UUID `json:"post_id"`
	MediaID   pgtype.UUID `json:"media_id"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) AttachMediaToPost(ctx context.Context, arg AttachMediaToPostParams) (PostMedium, error) {
	row := q.db.QueryRow(ctx, attachMediaToPost, arg.PostID, arg.MediaID, arg.SortOrder)
	var i PostMedium
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MediaID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (user_id, bucket, object_key, content_type, size_bytes, width, height, status, thumbnail_object_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, user_id, bucket, object_key, content_type, size_bytes, width, height, status, etag, created_at, updated_at, thumbnail_object_key
`

type CreateMediaParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	Bucket             string      `json:"bucket"`
	ObjectKey          string      `json:"object_key"`
	ContentType        string      `json:"content_type"`
	SizeBytes          int32       `json:"size_bytes"`
	Width              pgtype.Int4 `json:"width"`
	Height             pgtype.Int4 `json:"height"`
	Status             string      `json:"status"`
	ThumbnailObjectKey pgtype.Text `json:"thumbnail_object_key"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.UserID,
		arg.Bucket,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.Status,
		arg.ThumbnailObjectKey,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Bucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Status,
		&i.Etag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailObjectKey,
	)
	return i, err
}

const deleteStagedMediaOlderThan = `-- name: DeleteStagedMediaOlderThan :exec
DELETE FROM media
WHERE status = 'staged' AND created_at < $1
`

func (q *Queries) DeleteStagedMediaOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteStagedMediaOlderThan, createdAt)
	return err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, org_id, user_id, bucket, object_key, content_type, size_bytes, width, height, status, etag, created_at, updated_at, thumbnail_object_key FROM media WHERE id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, id pgtype.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Bucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Status,
		&i.Etag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailObjectKey,
	)
	return i, err
}

const getMediaByObjectKey = `-- name: GetMediaByObjectKey :one
SELECT id, org_id, user_id, bucket, object_key, content_type, size_bytes, width, height, status, etag, created_at, updated_at, thumbnail_object_key FROM media WHERE object_key = $1
`

func (q *Queries) GetMediaByObjectKey(ctx context.Context, objectKey string) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByObjectKey, objectKey)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Bucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Status,
		&i.Etag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailObjectKey,
	)
	return i, err
}

const getMediaForPost = `-- name: GetMediaForPost :many
SELECT m.id, m.org_id, m.user_id, m.bucket, m.object_key, m.content_type, m.size_bytes, m.width, m.height, m.status, m.etag, m.created_at, m.updated_at, m.thumbnail_object_key FROM media m
JOIN post_media pm ON m.id = pm.media_id
WHERE pm.post_id = $1
AND m.object_key NOT LIKE '%_thumb.jpg'
ORDER BY pm.sort_order ASC
`

func (q *Queries) GetMediaForPost(ctx context.Context, postID pgtype.UUID) ([]Medium, error) {
	rows, err := q.db.Query(ctx, getMediaForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Bucket,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.Status,
			&i.Etag,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbnailObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThumbnailForPost = `-- name: GetThumbnailForPost :one
SELECT object_key FROM media
WHERE object_key LIKE $1 || '%_thumb.jpg'
AND object_key LIKE '%_thumb.jpg'
LIMIT 1
`

func (q *Queries) GetThumbnailForPost(ctx context.Context, dollar_1 pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, getThumbnailForPost, dollar_1)
	var object_key string
	err := row.Scan(&object_key)
	return object_key, err
}

const updateMediaMetadata = `-- name: UpdateMediaMetadata :one
UPDATE media
SET etag = $2, size_bytes = $3, width = $4, height = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, user_id, bucket, object_key, content_type, size_bytes, width, height, status, etag, created_at, updated_at, thumbnail_object_key
`

type UpdateMediaMetadataParams struct {
	ID        pgtype.UUID `json:"id"`
	Etag      pgtype.Text `json:"etag"`
	SizeBytes int32       `json:"size_bytes"`
	Width     pgtype.Int4 `json:"width"`
	Height    pgtype.Int4 `json:"height"`
}

func (q *Queries) UpdateMediaMetadata(ctx context.Context, arg UpdateMediaMetadataParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaMetadata,
		arg.ID,
		arg.Etag,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Bucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Status,
		&i.Etag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailObjectKey,
	)
	return i, err
}

const updateMediaStatus = `-- name: UpdateMediaStatus :one
UPDATE media
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, user_id, bucket, object_key, content_type, size_bytes, width, height, status, etag, created_at, updated_at, thumbnail_object_key
`

type UpdateMediaStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateMediaStatus(ctx context.Context, arg UpdateMediaStatusParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaStatus, arg.ID, arg.Status)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Bucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.Status,
		&i.Etag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailObjectKey,
	)
	return i, err
}
