// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BeerPostDetail struct {
	ID        pgtype.UUID        `json:"id"`
	Brewery   pgtype.Text        `json:"brewery"`
	Abv       pgtype.Numeric     `json:"abv"`
	Ibu       pgtype.Int4        `json:"ibu"`
	Acidity   pgtype.Text        `json:"acidity"`
	BeerStyle pgtype.Text        `json:"beer_style"`
	Serving   pgtype.Text        `json:"serving"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Beverage struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Brand           pgtype.Text        `json:"brand"`
	Category        string             `json:"category"`
	Vintage         pgtype.Text        `json:"vintage"`
	ImageUrl        pgtype.Text        `json:"image_url"`
	NameNormalized  string             `json:"name_normalized"`
	BrandNormalized pgtype.Text        `json:"brand_normalized"`
	TotalReviews    pgtype.Int4        `json:"total_reviews"`
	AvgRating       pgtype.Numeric     `json:"avg_rating"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type BeverageSummary struct {
	BeverageID        pgtype.UUID        `json:"beverage_id"`
	SummaryText       string             `json:"summary_text"`
	DescriptorsJson   []byte             `json:"descriptors_json"`
	ProsJson          []byte             `json:"pros_json"`
	ConsJson          []byte             `json:"cons_json"`
	CoverageScore     pgtype.Numeric     `json:"coverage_score"`
	SourceReviewCount pgtype.Int4        `json:"source_review_count"`
	Model             pgtype.Text        `json:"model"`
	ModelVersion      pgtype.Text        `json:"model_version"`
	GeneratedAt       pgtype.Timestamptz `json:"generated_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type BeverageTagAggregate struct {
	BeverageID pgtype.UUID        `json:"beverage_id"`
	Tag        string             `json:"tag"`
	TagType    string             `json:"tag_type"`
	Count      int32              `json:"count"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CocktailPostDetail struct {
	ID             pgtype.UUID        `json:"id"`
	BaseSpirit     pgtype.Text        `json:"base_spirit"`
	CocktailFamily pgtype.Text        `json:"cocktail_family"`
	Preparation    pgtype.Text        `json:"preparation"`
	Presentation   pgtype.Text        `json:"presentation"`
	Garnish        pgtype.Text        `json:"garnish"`
	Sweetness      pgtype.Text        `json:"sweetness"`
	Booziness      pgtype.Text        `json:"booziness"`
	Balance        pgtype.Text        `json:"balance"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Medium struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	Bucket             string             `json:"bucket"`
	ObjectKey          string             `json:"object_key"`
	ContentType        string             `json:"content_type"`
	SizeBytes          int32              `json:"size_bytes"`
	Width              pgtype.Int4        `json:"width"`
	Height             pgtype.Int4        `json:"height"`
	Status             string             `json:"status"`
	Etag               pgtype.Text        `json:"etag"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ThumbnailObjectKey pgtype.Text        `json:"thumbnail_object_key"`
}

type OpenaiJob struct {
	ID         pgtype.UUID        `json:"id"`
	JobType    string             `json:"job_type"`
	BeverageID pgtype.UUID        `json:"beverage_id"`
	PostID     pgtype.UUID        `json:"post_id"`
	Status     string             `json:"status"`
	Attempts   pgtype.Int4        `json:"attempts"`
	LastError  pgtype.Text        `json:"last_error"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Post struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                pgtype.UUID        `json:"user_id"`
	VenueID               pgtype.UUID        `json:"venue_id"`
	DrinkName             string             `json:"drink_name"`
	DrinkCategory         string             `json:"drink_category"`
	Stars                 pgtype.Int4        `json:"stars"`
	Notes                 pgtype.Text        `json:"notes"`
	WinePostDetailsID     pgtype.UUID        `json:"wine_post_details_id"`
	BeerPostDetailsID     pgtype.UUID        `json:"beer_post_details_id"`
	CocktailPostDetailsID pgtype.UUID        `json:"cocktail_post_details_id"`
	PriceCents            pgtype.Int4        `json:"price_cents"`
	PhotoUrl              pgtype.Text        `json:"photo_url"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Score                 pgtype.Numeric     `json:"score"`
	BeverageID            pgtype.UUID        `json:"beverage_id"`
}

type PostMedium struct {
	ID        pgtype.UUID        `json:"id"`
	PostID    pgtype.UUID        `json:"post_id"`
	MediaID   pgtype.UUID        `json:"media_id"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostTag struct {
	ID         pgtype.UUID        `json:"id"`
	PostID     pgtype.UUID        `json:"post_id"`
	BeverageID pgtype.UUID        `json:"beverage_id"`
	Tag        string             `json:"tag"`
	TagType    string             `json:"tag_type"`
	Confidence pgtype.Numeric     `json:"confidence"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RecommendationFeedback struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	BeverageID   pgtype.UUID        `json:"beverage_id"`
	FeedbackType string             `json:"feedback_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	Handle        string             `json:"handle"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	Bio           pgtype.Text        `json:"bio"`
	OauthProvider pgtype.Text        `json:"oauth_provider"`
	OauthSubject  pgtype.Text        `json:"oauth_subject"`
	PasswordHash  string             `json:"password_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserEmbedding struct {
	UserID          pgtype.UUID        `json:"user_id"`
	Category        string             `json:"category"`
	EmbeddingText   string             `json:"embedding_text"`
	EmbeddingVector []float32          `json:"embedding_vector"`
	Model           pgtype.Text        `json:"model"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserTasteProfile struct {
	UserID           pgtype.UUID        `json:"user_id"`
	Category         string             `json:"category"`
	LikedTagsJson    []byte             `json:"liked_tags_json"`
	DislikedTagsJson []byte             `json:"disliked_tags_json"`
	MeanRating       pgtype.Numeric     `json:"mean_rating"`
	StdRating        pgtype.Numeric     `json:"std_rating"`
	PostCount        pgtype.Int4        `json:"post_count"`
	LastComputedAt   pgtype.Timestamptz `json:"last_computed_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Venue struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	VenueType       string             `json:"venue_type"`
	Address         pgtype.Text        `json:"address"`
	City            pgtype.Text        `json:"city"`
	State           pgtype.Text        `json:"state"`
	Country         pgtype.Text        `json:"country"`
	Lat             pgtype.Float8      `json:"lat"`
	Lng             pgtype.Float8      `json:"lng"`
	HasBeer         pgtype.Int2        `json:"has_beer"`
	HasWine         pgtype.Int2        `json:"has_wine"`
	HasCocktails    pgtype.Int2        `json:"has_cocktails"`
	MapProvider     pgtype.Text        `json:"map_provider"`
	ExternalPlaceID pgtype.Text        `json:"external_place_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	UserID          pgtype.UUID        `json:"user_id"`
	IsPublic        pgtype.Int2        `json:"is_public"`
}

type WinePostDetail struct {
	ID        pgtype.UUID        `json:"id"`
	Sweetness pgtype.Text        `json:"sweetness"`
	Body      pgtype.Text        `json:"body"`
	Tannin    pgtype.Text        `json:"tannin"`
	Acidity   pgtype.Text        `json:"acidity"`
	WineStyle pgtype.Text        `json:"wine_style"`
	Varietal  pgtype.Text        `json:"varietal"`
	Region    pgtype.Text        `json:"region"`
	Vintage   pgtype.Text        `json:"vintage"`
	Winery    pgtype.Text        `json:"winery"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
