// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BeerPostDetail struct {
	ID        pgtype.UUID        `json:"id"`
	Brewery   pgtype.Text        `json:"brewery"`
	Abv       pgtype.Numeric     `json:"abv"`
	Ibu       pgtype.Int4        `json:"ibu"`
	Acidity   pgtype.Text        `json:"acidity"`
	BeerStyle pgtype.Text        `json:"beer_style"`
	Serving   pgtype.Text        `json:"serving"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CocktailPostDetail struct {
	ID             pgtype.UUID        `json:"id"`
	BaseSpirit     pgtype.Text        `json:"base_spirit"`
	CocktailFamily pgtype.Text        `json:"cocktail_family"`
	Preparation    pgtype.Text        `json:"preparation"`
	Presentation   pgtype.Text        `json:"presentation"`
	Garnish        pgtype.Text        `json:"garnish"`
	Sweetness      pgtype.Text        `json:"sweetness"`
	Booziness      pgtype.Text        `json:"booziness"`
	Balance        pgtype.Text        `json:"balance"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Post struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                pgtype.UUID        `json:"user_id"`
	VenueID               pgtype.UUID        `json:"venue_id"`
	DrinkName             string             `json:"drink_name"`
	DrinkCategory         string             `json:"drink_category"`
	Stars                 pgtype.Int4        `json:"stars"`
	Notes                 pgtype.Text        `json:"notes"`
	WinePostDetailsID     pgtype.UUID        `json:"wine_post_details_id"`
	BeerPostDetailsID     pgtype.UUID        `json:"beer_post_details_id"`
	CocktailPostDetailsID pgtype.UUID        `json:"cocktail_post_details_id"`
	PriceCents            pgtype.Int4        `json:"price_cents"`
	PhotoUrl              pgtype.Text        `json:"photo_url"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	Handle        string             `json:"handle"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	Bio           pgtype.Text        `json:"bio"`
	OauthProvider pgtype.Text        `json:"oauth_provider"`
	OauthSubject  pgtype.Text        `json:"oauth_subject"`
	PasswordHash  string             `json:"password_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Venue struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	VenueType       string             `json:"venue_type"`
	Address         pgtype.Text        `json:"address"`
	City            pgtype.Text        `json:"city"`
	State           pgtype.Text        `json:"state"`
	Country         pgtype.Text        `json:"country"`
	Lat             pgtype.Float8      `json:"lat"`
	Lng             pgtype.Float8      `json:"lng"`
	HasBeer         pgtype.Int2        `json:"has_beer"`
	HasWine         pgtype.Int2        `json:"has_wine"`
	HasCocktails    pgtype.Int2        `json:"has_cocktails"`
	MapProvider     pgtype.Text        `json:"map_provider"`
	ExternalPlaceID pgtype.Text        `json:"external_place_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	UserID          pgtype.UUID        `json:"user_id"`
	IsPublic        pgtype.Int2        `json:"is_public"`
}

type WinePostDetail struct {
	ID        pgtype.UUID        `json:"id"`
	Sweetness pgtype.Text        `json:"sweetness"`
	Body      pgtype.Text        `json:"body"`
	Tannin    pgtype.Text        `json:"tannin"`
	Acidity   pgtype.Text        `json:"acidity"`
	WineStyle pgtype.Text        `json:"wine_style"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Varietal  pgtype.Text        `json:"varietal"`
	Region    pgtype.Text        `json:"region"`
	Vintage   pgtype.Text        `json:"vintage"`
	Winery    pgtype.Text        `json:"winery"`
}
