// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBeerPostDetails = `-- name: CreateBeerPostDetails :one
INSERT INTO beer_post_details (brewery, abv, ibu, acidity, beer_style, serving)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, brewery, abv, ibu, acidity, beer_style, serving, created_at, updated_at
`

type CreateBeerPostDetailsParams struct {
	Brewery   pgtype.Text    `json:"brewery"`
	Abv       pgtype.Numeric `json:"abv"`
	Ibu       pgtype.Int4    `json:"ibu"`
	Acidity   pgtype.Text    `json:"acidity"`
	BeerStyle pgtype.Text    `json:"beer_style"`
	Serving   pgtype.Text    `json:"serving"`
}

func (q *Queries) CreateBeerPostDetails(ctx context.Context, arg CreateBeerPostDetailsParams) (BeerPostDetail, error) {
	row := q.db.QueryRow(ctx, createBeerPostDetails,
		arg.Brewery,
		arg.Abv,
		arg.Ibu,
		arg.Acidity,
		arg.BeerStyle,
		arg.Serving,
	)
	var i BeerPostDetail
	err := row.Scan(
		&i.ID,
		&i.Brewery,
		&i.Abv,
		&i.Ibu,
		&i.Acidity,
		&i.BeerStyle,
		&i.Serving,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCocktailPostDetails = `-- name: CreateCocktailPostDetails :one
INSERT INTO cocktail_post_details (base_spirit, cocktail_family, preparation, presentation, garnish, sweetness, booziness, balance)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, base_spirit, cocktail_family, preparation, presentation, garnish, sweetness, booziness, balance, created_at, updated_at
`

type CreateCocktailPostDetailsParams struct {
	BaseSpirit     pgtype.Text `json:"base_spirit"`
	CocktailFamily pgtype.Text `json:"cocktail_family"`
	Preparation    pgtype.Text `json:"preparation"`
	Presentation   pgtype.Text `json:"presentation"`
	Garnish        pgtype.Text `json:"garnish"`
	Sweetness      pgtype.Text `json:"sweetness"`
	Booziness      pgtype.Text `json:"booziness"`
	Balance        pgtype.Text `json:"balance"`
}

func (q *Queries) CreateCocktailPostDetails(ctx context.Context, arg CreateCocktailPostDetailsParams) (CocktailPostDetail, error) {
	row := q.db.QueryRow(ctx, createCocktailPostDetails,
		arg.BaseSpirit,
		arg.CocktailFamily,
		arg.Preparation,
		arg.Presentation,
		arg.Garnish,
		arg.Sweetness,
		arg.Booziness,
		arg.Balance,
	)
	var i CocktailPostDetail
	err := row.Scan(
		&i.ID,
		&i.BaseSpirit,
		&i.CocktailFamily,
		&i.Preparation,
		&i.Presentation,
		&i.Garnish,
		&i.Sweetness,
		&i.Booziness,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, venue_id, drink_name, drink_category, stars, notes, beer_post_details_id, wine_post_details_id, cocktail_post_details_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, venue_id, drink_name, drink_category, stars, notes, wine_post_details_id, beer_post_details_id, cocktail_post_details_id, price_cents, photo_url, created_at, updated_at
`

type CreatePostParams struct {
	UserID                pgtype.UUID `json:"user_id"`
	VenueID               pgtype.UUID `json:"venue_id"`
	DrinkName             string      `json:"drink_name"`
	DrinkCategory         string      `json:"drink_category"`
	Stars                 int32       `json:"stars"`
	Notes                 string      `json:"notes"`
	BeerPostDetailsID     pgtype.UUID `json:"beer_post_details_id"`
	WinePostDetailsID     pgtype.UUID `json:"wine_post_details_id"`
	CocktailPostDetailsID pgtype.UUID `json:"cocktail_post_details_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.UserID,
		arg.VenueID,
		arg.DrinkName,
		arg.DrinkCategory,
		arg.Stars,
		arg.Notes,
		arg.BeerPostDetailsID,
		arg.WinePostDetailsID,
		arg.CocktailPostDetailsID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VenueID,
		&i.DrinkName,
		&i.DrinkCategory,
		&i.Stars,
		&i.Notes,
		&i.WinePostDetailsID,
		&i.BeerPostDetailsID,
		&i.CocktailPostDetailsID,
		&i.PriceCents,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWinePostDetails = `-- name: CreateWinePostDetails :one
INSERT INTO wine_post_details (sweetness, body, tannin, acidity, wine_style)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, sweetness, body, tannin, acidity, wine_style, created_at, updated_at
`

type CreateWinePostDetailsParams struct {
	Sweetness pgtype.Text `json:"sweetness"`
	Body      pgtype.Text `json:"body"`
	Tannin    pgtype.Text `json:"tannin"`
	Acidity   pgtype.Text `json:"acidity"`
	WineStyle pgtype.Text `json:"wine_style"`
}

func (q *Queries) CreateWinePostDetails(ctx context.Context, arg CreateWinePostDetailsParams) (WinePostDetail, error) {
	row := q.db.QueryRow(ctx, createWinePostDetails,
		arg.Sweetness,
		arg.Body,
		arg.Tannin,
		arg.Acidity,
		arg.WineStyle,
	)
	var i WinePostDetail
	err := row.Scan(
		&i.ID,
		&i.Sweetness,
		&i.Body,
		&i.Tannin,
		&i.Acidity,
		&i.WineStyle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getBeerPostDetails = `-- name: GetBeerPostDetails :one
SELECT id, brewery, abv, ibu, acidity, beer_style, serving, created_at, updated_at FROM beer_post_details WHERE id = $1
`

func (q *Queries) GetBeerPostDetails(ctx context.Context, id pgtype.UUID) (BeerPostDetail, error) {
	row := q.db.QueryRow(ctx, getBeerPostDetails, id)
	var i BeerPostDetail
	err := row.Scan(
		&i.ID,
		&i.Brewery,
		&i.Abv,
		&i.Ibu,
		&i.Acidity,
		&i.BeerStyle,
		&i.Serving,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCocktailPostDetails = `-- name: GetCocktailPostDetails :one
SELECT id, base_spirit, cocktail_family, preparation, presentation, garnish, sweetness, booziness, balance, created_at, updated_at FROM cocktail_post_details WHERE id = $1
`

func (q *Queries) GetCocktailPostDetails(ctx context.Context, id pgtype.UUID) (CocktailPostDetail, error) {
	row := q.db.QueryRow(ctx, getCocktailPostDetails, id)
	var i CocktailPostDetail
	err := row.Scan(
		&i.ID,
		&i.BaseSpirit,
		&i.CocktailFamily,
		&i.Preparation,
		&i.Presentation,
		&i.Garnish,
		&i.Sweetness,
		&i.Booziness,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, user_id, venue_id, drink_name, drink_category, stars, notes, wine_post_details_id, beer_post_details_id, cocktail_post_details_id, price_cents, photo_url, created_at, updated_at FROM posts WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VenueID,
		&i.DrinkName,
		&i.DrinkCategory,
		&i.Stars,
		&i.Notes,
		&i.WinePostDetailsID,
		&i.BeerPostDetailsID,
		&i.CocktailPostDetailsID,
		&i.PriceCents,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWinePostDetails = `-- name: GetWinePostDetails :one
SELECT id, sweetness, body, tannin, acidity, wine_style, created_at, updated_at FROM wine_post_details WHERE id = $1
`

func (q *Queries) GetWinePostDetails(ctx context.Context, id pgtype.UUID) (WinePostDetail, error) {
	row := q.db.QueryRow(ctx, getWinePostDetails, id)
	var i WinePostDetail
	err := row.Scan(
		&i.ID,
		&i.Sweetness,
		&i.Body,
		&i.Tannin,
		&i.Acidity,
		&i.WineStyle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, user_id, venue_id, drink_name, drink_category, stars, notes, wine_post_details_id, beer_post_details_id, cocktail_post_details_id, price_cents, photo_url, created_at, updated_at FROM posts ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListPosts(ctx context.Context, limit int32) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VenueID,
			&i.DrinkName,
			&i.DrinkCategory,
			&i.Stars,
			&i.Notes,
			&i.WinePostDetailsID,
			&i.BeerPostDetailsID,
			&i.CocktailPostDetailsID,
			&i.PriceCents,
			&i.PhotoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByExternalPlaceID = `-- name: ListPostsByExternalPlaceID :many
SELECT p.id, p.user_id, p.venue_id, p.drink_name, p.drink_category, p.stars, p.notes, p.wine_post_details_id, p.beer_post_details_id, p.cocktail_post_details_id, p.price_cents, p.photo_url, p.created_at, p.updated_at FROM posts p
JOIN venues v ON p.venue_id = v.id
WHERE v.external_place_id = $1
ORDER BY p.created_at DESC
`

func (q *Queries) ListPostsByExternalPlaceID(ctx context.Context, externalPlaceID pgtype.Text) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByExternalPlaceID, externalPlaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VenueID,
			&i.DrinkName,
			&i.DrinkCategory,
			&i.Stars,
			&i.Notes,
			&i.WinePostDetailsID,
			&i.BeerPostDetailsID,
			&i.CocktailPostDetailsID,
			&i.PriceCents,
			&i.PhotoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBeerPostDetails = `-- name: UpdateBeerPostDetails :one
UPDATE beer_post_details
SET brewery = $2, abv = $3, ibu = $4, acidity = $5, beer_style = $6, serving = $7
WHERE id = $1
RETURNING id, brewery, abv, ibu, acidity, beer_style, serving, created_at, updated_at
`

type UpdateBeerPostDetailsParams struct {
	ID        pgtype.UUID    `json:"id"`
	Brewery   pgtype.Text    `json:"brewery"`
	Abv       pgtype.Numeric `json:"abv"`
	Ibu       pgtype.Int4    `json:"ibu"`
	Acidity   pgtype.Text    `json:"acidity"`
	BeerStyle pgtype.Text    `json:"beer_style"`
	Serving   pgtype.Text    `json:"serving"`
}

func (q *Queries) UpdateBeerPostDetails(ctx context.Context, arg UpdateBeerPostDetailsParams) (BeerPostDetail, error) {
	row := q.db.QueryRow(ctx, updateBeerPostDetails,
		arg.ID,
		arg.Brewery,
		arg.Abv,
		arg.Ibu,
		arg.Acidity,
		arg.BeerStyle,
		arg.Serving,
	)
	var i BeerPostDetail
	err := row.Scan(
		&i.ID,
		&i.Brewery,
		&i.Abv,
		&i.Ibu,
		&i.Acidity,
		&i.BeerStyle,
		&i.Serving,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCocktailPostDetails = `-- name: UpdateCocktailPostDetails :one
UPDATE cocktail_post_details
SET base_spirit = $2, cocktail_family = $3, preparation = $4, presentation = $5, garnish = $6, sweetness = $7, booziness = $8, balance = $9
WHERE id = $1
RETURNING id, base_spirit, cocktail_family, preparation, presentation, garnish, sweetness, booziness, balance, created_at, updated_at
`

type UpdateCocktailPostDetailsParams struct {
	ID             pgtype.UUID `json:"id"`
	BaseSpirit     pgtype.Text `json:"base_spirit"`
	CocktailFamily pgtype.Text `json:"cocktail_family"`
	Preparation    pgtype.Text `json:"preparation"`
	Presentation   pgtype.Text `json:"presentation"`
	Garnish        pgtype.Text `json:"garnish"`
	Sweetness      pgtype.Text `json:"sweetness"`
	Booziness      pgtype.Text `json:"booziness"`
	Balance        pgtype.Text `json:"balance"`
}

func (q *Queries) UpdateCocktailPostDetails(ctx context.Context, arg UpdateCocktailPostDetailsParams) (CocktailPostDetail, error) {
	row := q.db.QueryRow(ctx, updateCocktailPostDetails,
		arg.ID,
		arg.BaseSpirit,
		arg.CocktailFamily,
		arg.Preparation,
		arg.Presentation,
		arg.Garnish,
		arg.Sweetness,
		arg.Booziness,
		arg.Balance,
	)
	var i CocktailPostDetail
	err := row.Scan(
		&i.ID,
		&i.BaseSpirit,
		&i.CocktailFamily,
		&i.Preparation,
		&i.Presentation,
		&i.Garnish,
		&i.Sweetness,
		&i.Booziness,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET drink_name = $2, stars = $3, notes = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, venue_id, drink_name, drink_category, stars, notes, wine_post_details_id, beer_post_details_id, cocktail_post_details_id, price_cents, photo_url, created_at, updated_at
`

type UpdatePostParams struct {
	ID        pgtype.UUID `json:"id"`
	DrinkName string      `json:"drink_name"`
	Stars     int32       `json:"stars"`
	Notes     string      `json:"notes"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.DrinkName,
		arg.Stars,
		arg.Notes,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VenueID,
		&i.DrinkName,
		&i.DrinkCategory,
		&i.Stars,
		&i.Notes,
		&i.WinePostDetailsID,
		&i.BeerPostDetailsID,
		&i.CocktailPostDetailsID,
		&i.PriceCents,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWinePostDetails = `-- name: UpdateWinePostDetails :one
UPDATE wine_post_details
SET sweetness = $2, body = $3, tannin = $4, acidity = $5, wine_style = $6
WHERE id = $1
RETURNING id, sweetness, body, tannin, acidity, wine_style, created_at, updated_at
`

type UpdateWinePostDetailsParams struct {
	ID        pgtype.UUID `json:"id"`
	Sweetness pgtype.Text `json:"sweetness"`
	Body      pgtype.Text `json:"body"`
	Tannin    pgtype.Text `json:"tannin"`
	Acidity   pgtype.Text `json:"acidity"`
	WineStyle pgtype.Text `json:"wine_style"`
}

func (q *Queries) UpdateWinePostDetails(ctx context.Context, arg UpdateWinePostDetailsParams) (WinePostDetail, error) {
	row := q.db.QueryRow(ctx, updateWinePostDetails,
		arg.ID,
		arg.Sweetness,
		arg.Body,
		arg.Tannin,
		arg.Acidity,
		arg.WineStyle,
	)
	var i WinePostDetail
	err := row.Scan(
		&i.ID,
		&i.Sweetness,
		&i.Body,
		&i.Tannin,
		&i.Acidity,
		&i.WineStyle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
