// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AttachMediaToPost(ctx context.Context, arg AttachMediaToPostParams) (PostMedium, error)
	CreateBeerPostDetails(ctx context.Context, arg CreateBeerPostDetailsParams) (BeerPostDetail, error)
	CreateCocktailPostDetails(ctx context.Context, arg CreateCocktailPostDetailsParams) (CocktailPostDetail, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error)
	CreateWinePostDetails(ctx context.Context, arg CreateWinePostDetailsParams) (WinePostDetail, error)
	DeletePost(ctx context.Context, id pgtype.UUID) error
	DeleteStagedMediaOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error
	GetBeerPostDetails(ctx context.Context, id pgtype.UUID) (BeerPostDetail, error)
	GetCocktailPostDetails(ctx context.Context, id pgtype.UUID) (CocktailPostDetail, error)
	GetMediaByID(ctx context.Context, id pgtype.UUID) (Medium, error)
	GetMediaByObjectKey(ctx context.Context, objectKey string) (Medium, error)
	GetMediaForPost(ctx context.Context, postID pgtype.UUID) ([]Medium, error)
	GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetThumbnailForPost(ctx context.Context, dollar_1 pgtype.Text) (string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailOrHandle(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetVenueByExternalPlaceID(ctx context.Context, externalPlaceID pgtype.Text) (Venue, error)
	GetVenueByID(ctx context.Context, id pgtype.UUID) (Venue, error)
	GetWinePostDetails(ctx context.Context, id pgtype.UUID) (WinePostDetail, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	ListPosts(ctx context.Context, limit int32) ([]Post, error)
	ListPostsByExternalPlaceID(ctx context.Context, externalPlaceID pgtype.Text) ([]Post, error)
	ListUsers(ctx context.Context, limit int32) ([]User, error)
	ListVenues(ctx context.Context, arg ListVenuesParams) ([]Venue, error)
	RevokeAllRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	SearchVenues(ctx context.Context, arg SearchVenuesParams) ([]Venue, error)
	UpdateBeerPostDetails(ctx context.Context, arg UpdateBeerPostDetailsParams) (BeerPostDetail, error)
	UpdateCocktailPostDetails(ctx context.Context, arg UpdateCocktailPostDetailsParams) (CocktailPostDetail, error)
	UpdateMediaMetadata(ctx context.Context, arg UpdateMediaMetadataParams) (Medium, error)
	UpdateMediaStatus(ctx context.Context, arg UpdateMediaStatusParams) (Medium, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateWinePostDetails(ctx context.Context, arg UpdateWinePostDetailsParams) (WinePostDetail, error)
}

var _ Querier = (*Queries)(nil)
